publicHoistPattern:
  - "*eslint*"
  - "*prettier*"
  - "*vitest*"
  - "typescript"
  - "*rimraf*"
  - "*cross-env*"

minimumReleaseAgeExclude:
  - "@types/node@24.13.1"
  - fuse.js@7.4.2
  - undici@7.27.2

allowBuilds:
  esbuild: true
  tldjs: true
